name: Tests
on: [ push, pull-request ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile
    - run: yarn build
  
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - run: yarn lint
      - run: yarn test
